### ISSUE TITLE
Can we make PR-Gatekeeper policy branch specific

### ISSUE THREAD

**Issue by mohan-the-octocat** [octodemo/pr-gatekeeper#349]
## What
Currently PR Gatekeeper applies the policy defined in the `approve-config.yml` file. This set-up works fine when there is single-step PR process involving a simple branching strategy (`dev-release-main`) or when all approvals for a PR are within a single PR.

## But 
In situations where there is a more deeper branching strategy (`dev-feature-release-main`) involving a multi-stage PR process with different approvers at each stage, the `approve-config.yml` is unable to define branch-specific approvers.

## And
Solving this thru' the branch-level `CODEOWNERS` file is not feasible, since having different versions of `CODEOWNERS` in different branches is not possible (they get merged during a PR!)

## So
If the `approve-config.yml` file can be a parametrized input that is passed at runtime to PR Gatekeeper, repo owners can customize the approval rules based on branch level requirements

**Comment by mohan-the-octocat** [comment]
So, I see the config file is accepted as an input. Let me try and see if this fits the requirement here and revert.

**Comment by yuichielectric** [comment]
@mohan-the-octocat Yeah, you can pass the path to the config file as input, so you can, for example, separate the config file for PR to the dev branch and the config file for PR to the release branch. This would allow us to define separate approval flows for each, what do you think?

**Comment by mohan-the-octocat** [comment]
@yuichielectric - 🙇 for those inputs.

When I try to [pass in](https://github.com/octodemo/mtc-bookworks/blob/main/.github/workflows/pr-gatekeeper.yml) a second config file like [this one](https://github.com/octodemo/mtc-bookworks/blob/main/.github/approve_config_2.yml) to the [job](https://github.com/octodemo/mtc-bookworks/actions/runs/3148865651), I start seeing our old behavior 😯 

<img width="729" alt="image" src="https://user-images.githubusercontent.com/83639549/192947859-8c1c1288-8025-4ba8-8e16-114411773e76.png">

Not sure if I am doing something wrong, Let me know!

**Comment by yuichielectric** [comment]
Got it, let me take a look 👁️

**Comment by yuichielectric** [comment]
@mohan-the-octocat `octodemo/pr-gatekeeper@v1.0.0` has that bug (the old behaviour), so could you update the actions workflow yaml file so that you use `v1.0.1` or above?

**Comment by mohan-the-octocat** [comment]
Too bad. The bug was between the computer and the chair. Thanks!

**Comment by yuichielectric** [comment]
No worries at all ❤️
